### ISSUE TITLE
Test the Arduino (3 days)

### ISSUE THREAD

**Issue by Jingying84** [NUSCUTECenter/Season-Traveller-2#28]

**Comment by pravar93** [comment]
If required, upload the following code to the Arduino UNO for:
1. Establishing serial communication
2. Printing received data to the serial monitor
3. Sending back the received data to Unity

`
void setup()
{
  Serial.begin(115200);  // Initialise serial communication at baud rate of 115200
}

void loop()
{
  if (Serial.available())
  {
    Serial.write(Serial.read()); // Send and print received data
    Serial.println();   // Print line feed character
  }
}
`
